name: Build and Release
on:
  push:
    tags: ["v*"]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install and Build
        run: |
          bun install
          bun run scripts/release.ts

      - name: Zip Release
        run: Compress-Archive -Path ./roobie_cms_release/* -DestinationPath RoobieCMS_Windows.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: RoobieCMS_Windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
